// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: p2p.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractValidator_ValidarContrato_FullMethodName = "/p2p.ContractValidator/ValidarContrato"
)

// ContractValidatorClient is the client API for ContractValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio Validador de Contratos en Caliente (Zero-Trust & Sanitize)
type ContractValidatorClient interface {
	ValidarContrato(ctx context.Context, in *OrdenEnergyRequest, opts ...grpc.CallOption) (*ValidacionResponse, error)
}

type contractValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewContractValidatorClient(cc grpc.ClientConnInterface) ContractValidatorClient {
	return &contractValidatorClient{cc}
}

func (c *contractValidatorClient) ValidarContrato(ctx context.Context, in *OrdenEnergyRequest, opts ...grpc.CallOption) (*ValidacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidacionResponse)
	err := c.cc.Invoke(ctx, ContractValidator_ValidarContrato_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractValidatorServer is the server API for ContractValidator service.
// All implementations must embed UnimplementedContractValidatorServer
// for forward compatibility.
//
// Servicio Validador de Contratos en Caliente (Zero-Trust & Sanitize)
type ContractValidatorServer interface {
	ValidarContrato(context.Context, *OrdenEnergyRequest) (*ValidacionResponse, error)
	mustEmbedUnimplementedContractValidatorServer()
}

// UnimplementedContractValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractValidatorServer struct{}

func (UnimplementedContractValidatorServer) ValidarContrato(context.Context, *OrdenEnergyRequest) (*ValidacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidarContrato not implemented")
}
func (UnimplementedContractValidatorServer) mustEmbedUnimplementedContractValidatorServer() {}
func (UnimplementedContractValidatorServer) testEmbeddedByValue()                           {}

// UnsafeContractValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractValidatorServer will
// result in compilation errors.
type UnsafeContractValidatorServer interface {
	mustEmbedUnimplementedContractValidatorServer()
}

func RegisterContractValidatorServer(s grpc.ServiceRegistrar, srv ContractValidatorServer) {
	// If the following call pancis, it indicates UnimplementedContractValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractValidator_ServiceDesc, srv)
}

func _ContractValidator_ValidarContrato_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdenEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractValidatorServer).ValidarContrato(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractValidator_ValidarContrato_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractValidatorServer).ValidarContrato(ctx, req.(*OrdenEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractValidator_ServiceDesc is the grpc.ServiceDesc for ContractValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.ContractValidator",
	HandlerType: (*ContractValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidarContrato",
			Handler:    _ContractValidator_ValidarContrato_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}

const (
	Notificador_EnviarNotificacion_FullMethodName = "/p2p.Notificador/EnviarNotificacion"
)

// NotificadorClient is the client API for Notificador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio del Notificador de Métricas P2P & Dispatcher Bidireccional
type NotificadorClient interface {
	EnviarNotificacion(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*NotificacionResponse, error)
}

type notificadorClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificadorClient(cc grpc.ClientConnInterface) NotificadorClient {
	return &notificadorClient{cc}
}

func (c *notificadorClient) EnviarNotificacion(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*NotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificacionResponse)
	err := c.cc.Invoke(ctx, Notificador_EnviarNotificacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificadorServer is the server API for Notificador service.
// All implementations must embed UnimplementedNotificadorServer
// for forward compatibility.
//
// Servicio del Notificador de Métricas P2P & Dispatcher Bidireccional
type NotificadorServer interface {
	EnviarNotificacion(context.Context, *MatchRequest) (*NotificacionResponse, error)
	mustEmbedUnimplementedNotificadorServer()
}

// UnimplementedNotificadorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificadorServer struct{}

func (UnimplementedNotificadorServer) EnviarNotificacion(context.Context, *MatchRequest) (*NotificacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarNotificacion not implemented")
}
func (UnimplementedNotificadorServer) mustEmbedUnimplementedNotificadorServer() {}
func (UnimplementedNotificadorServer) testEmbeddedByValue()                     {}

// UnsafeNotificadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificadorServer will
// result in compilation errors.
type UnsafeNotificadorServer interface {
	mustEmbedUnimplementedNotificadorServer()
}

func RegisterNotificadorServer(s grpc.ServiceRegistrar, srv NotificadorServer) {
	// If the following call pancis, it indicates UnimplementedNotificadorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notificador_ServiceDesc, srv)
}

func _Notificador_EnviarNotificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificadorServer).EnviarNotificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notificador_EnviarNotificacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificadorServer).EnviarNotificacion(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notificador_ServiceDesc is the grpc.ServiceDesc for Notificador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notificador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.Notificador",
	HandlerType: (*NotificadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarNotificacion",
			Handler:    _Notificador_EnviarNotificacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}

const (
	MatchingEngine_CrearOrden_FullMethodName = "/p2p.MatchingEngine/CrearOrden"
)

// MatchingEngineClient is the client API for MatchingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio del Matching Engine P2P
type MatchingEngineClient interface {
	CrearOrden(ctx context.Context, in *OrdenEnergyRequest, opts ...grpc.CallOption) (*OrdenEnergyResponse, error)
}

type matchingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineClient(cc grpc.ClientConnInterface) MatchingEngineClient {
	return &matchingEngineClient{cc}
}

func (c *matchingEngineClient) CrearOrden(ctx context.Context, in *OrdenEnergyRequest, opts ...grpc.CallOption) (*OrdenEnergyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrdenEnergyResponse)
	err := c.cc.Invoke(ctx, MatchingEngine_CrearOrden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingEngineServer is the server API for MatchingEngine service.
// All implementations must embed UnimplementedMatchingEngineServer
// for forward compatibility.
//
// Servicio del Matching Engine P2P
type MatchingEngineServer interface {
	CrearOrden(context.Context, *OrdenEnergyRequest) (*OrdenEnergyResponse, error)
	mustEmbedUnimplementedMatchingEngineServer()
}

// UnimplementedMatchingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingEngineServer struct{}

func (UnimplementedMatchingEngineServer) CrearOrden(context.Context, *OrdenEnergyRequest) (*OrdenEnergyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearOrden not implemented")
}
func (UnimplementedMatchingEngineServer) mustEmbedUnimplementedMatchingEngineServer() {}
func (UnimplementedMatchingEngineServer) testEmbeddedByValue()                        {}

// UnsafeMatchingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServer will
// result in compilation errors.
type UnsafeMatchingEngineServer interface {
	mustEmbedUnimplementedMatchingEngineServer()
}

func RegisterMatchingEngineServer(s grpc.ServiceRegistrar, srv MatchingEngineServer) {
	// If the following call pancis, it indicates UnimplementedMatchingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingEngine_ServiceDesc, srv)
}

func _MatchingEngine_CrearOrden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdenEnergyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).CrearOrden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_CrearOrden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).CrearOrden(ctx, req.(*OrdenEnergyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingEngine_ServiceDesc is the grpc.ServiceDesc for MatchingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.MatchingEngine",
	HandlerType: (*MatchingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearOrden",
			Handler:    _MatchingEngine_CrearOrden_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}
